package keymap

// Defaults are rush's own keys, as its key handling is written. Keys that
// only edit text (arrows in a box, ctrl+a, backspace) aren't here: they
// belong to the box, not to an action. None needs ⌥: where no ctrl or
// shift key is free, ctrl+] then the letter is the chord for its ⌥ key.
// ⌥d, ⌥f, ⌥c and ⌥b are the box's word keys, so their commands are the
// chord alone.
var Defaults = []Action{
	{ID: "guide.open", Context: Any, Title: "keyboard shortcuts for this view", Keys: []string{"f1"}, Runs: true},
	{ID: "bar.open", Context: Global, Title: "the command bar", Keys: []string{"ctrl+k", "super+k"}},
	{ID: "bar.scope", Context: Global, Title: "the command bar, next scope", Keys: []string{"ctrl+f"}},
	{ID: "quit", Context: Global, Title: "quit rush", Keys: []string{"ctrl+q"}},
	{ID: "zen", Context: Global, Title: "Zen on and off", Keys: []string{"ctrl+z"}},
	{ID: "place.prev", Context: Global, Title: "the place before", Keys: []string{",", "<"}},
	{ID: "place.next", Context: Global, Title: "the next place", Keys: []string{".", ">", "ctrl+\\"}},
	{ID: "profile.pick", Context: Global, Title: "switch the default profile or provider", Keys: []string{"ctrl+] w", "alt+w"}},

	{ID: "list.up", Context: List, Title: "the agent above", Keys: []string{"up"}},
	{ID: "list.down", Context: List, Title: "the agent below", Keys: []string{"down"}},
	{ID: "list.pageup", Context: List, Title: "ten agents up", Keys: []string{"pgup"}},
	{ID: "list.pagedown", Context: List, Title: "ten agents down", Keys: []string{"pgdown"}},
	{ID: "list.first", Context: List, Title: "the first agent", Keys: []string{"home", "shift+up"}},
	{ID: "list.last", Context: List, Title: "the last agent", Keys: []string{"end", "shift+down"}},
	{ID: "list.enter", Context: List, Title: "open or rename the agent, or send what's typed", Keys: []string{"enter"}},
	{ID: "list.open", Context: List, Title: "open the agent's Session", Keys: []string{"ctrl+o", "super+down"}},
	{ID: "list.right", Context: List, Title: "into the agent, or unfold a heading", Keys: []string{"right"}},
	{ID: "list.left", Context: List, Title: "fold the heading", Keys: []string{"left"}},
	{ID: "list.back", Context: List, Title: "clear, go back, or (twice) quit", Keys: []string{"esc"}},
	{ID: "list.rename", Context: List, Title: "rename the agent", Keys: []string{"ctrl+r"}},
	{ID: "list.start", Context: List, Title: "pick the next session's agent, model and effort", Keys: []string{"shift+tab", "alt+m"}},
	{ID: "list.worktree", Context: List, Title: "new sessions from a worktree agent: its worktree or main checkout", Keys: []string{"ctrl+] l", "alt+l"}},
	{ID: "list.folder", Context: List, Title: "choose the folder, or move the agent", Keys: []string{"ctrl+l"}},
	{ID: "list.pr", Context: List, Title: "open the agent's pull request", Keys: []string{"ctrl+y"}},
	{ID: "list.pin", Context: List, Title: "pin the agent", Keys: []string{"ctrl+t"}},
	{ID: "list.groupby", Context: List, Title: "group agents by the next", Keys: []string{"ctrl+s"}},
	{ID: "list.split", Context: List, Title: "split each section by project, or stop", Keys: []string{"ctrl+p"}},
	{ID: "list.stop", Context: List, Title: "hide (stop), restart, switch or delete the agent", Keys: []string{"ctrl+x"}},
	{ID: "list.done", Context: List, Title: "move the agent to Done", Keys: []string{"ctrl+d", "ctrl+] d"}},
	{ID: "list.go", Context: List, Title: "tell the agent to keep going", Keys: []string{"ctrl+b", "alt+g"}},
	{ID: "list.claudeview", Context: List, Title: "a Claude Code agent's screen or its summary, with nothing typed", Keys: []string{"v"}},
	{ID: "list.view.prev", Context: List, Title: "the agent's view before", Keys: []string{"["}},
	{ID: "list.view.next", Context: List, Title: "the agent's next view", Keys: []string{"]"}},
	{ID: "list.needs", Context: List, Title: "the next agent that needs you", Keys: []string{"ctrl+n"}},
	{ID: "list.split.less", Context: List, Title: "less of the screen for the list", Keys: []string{"shift+left", "alt+left"}},
	{ID: "list.split.more", Context: List, Title: "more of the screen for the list", Keys: []string{"shift+right", "alt+right"}},
	{ID: "list.help", Context: List, Title: "the keys, with nothing typed", Keys: []string{"?"}},
	{ID: "list.editor", Context: List, Title: "write what's typed in your editor", Keys: []string{"ctrl+g"}},
	{ID: "list.image", Context: List, Title: "paste an image", Keys: []string{"ctrl+v"}},
	{ID: "list.undo", Context: List, Title: "undo in the Prompt", Keys: []string{"super+z", "ctrl+_", "ctrl+/"}},
	{ID: "list.redo", Context: List, Title: "redo in the Prompt", Keys: []string{"shift+super+z"}},
	{ID: "list.focus", Context: List, Title: "into the Session, and back", Keys: []string{"tab", "{", "}"}},
	{ID: "list.filter", Context: List, Title: "filter agents by name or what's said", Keys: []string{"ctrl+] f"}, Runs: true},
	{ID: "list.toggle", Context: List, Title: "Agents beside the Session", Keys: []string{"ctrl+6", "ctrl+^", "ctrl+shift+6"}},

	// The same keys as the list's split and rename, which have them back
	// once the Prompt is empty.
	{ID: "prompt.stash", Context: Prompt, Title: "set what's typed aside; it comes back after you send", Keys: []string{"ctrl+p"}, Runs: true},
	{ID: "prompt.history", Context: Prompt, Title: "what you set aside, sent, cleared and replaced", Keys: []string{"ctrl+r"}, Runs: true},

	{ID: "page.prev", Context: Pages, Title: "the page before", Keys: []string{"[", "shift+tab"}},
	{ID: "page.next", Context: Pages, Title: "the next page", Keys: []string{"]", "tab"}},
	{ID: "page.go", Context: Pages, Title: "tell the agent to keep going", Keys: []string{"ctrl+b", "alt+g"}},
	{ID: "page.pr", Context: Pages, Title: "open the agent's pull request (Projects)", Keys: []string{"ctrl+y"}},

	{ID: "session.send", Context: Session, Title: "send now, the queue first", Keys: []string{"ctrl+enter", "ctrl+s"}},
	{ID: "session.enter", Context: Session, Title: "send the message from the composer", Keys: []string{"enter"}},
	{ID: "session.right", Context: Session, Title: "open what's picked", Keys: []string{"right"}},
	{ID: "session.back", Context: Session, Title: "back: off a row, out of a subagent, to Agents", Keys: []string{"left"}},
	{ID: "session.esc", Context: Session, Title: "clear, stop the turn, or leave; twice asks to close it", Keys: []string{"esc"}},
	{ID: "session.up", Context: Session, Title: "the row above", Keys: []string{"up"}},
	{ID: "session.down", Context: Session, Title: "the row below", Keys: []string{"down"}},
	{ID: "session.pageup", Context: Session, Title: "scroll up", Keys: []string{"pgup"}},
	{ID: "session.pagedown", Context: Session, Title: "scroll down", Keys: []string{"pgdown"}},
	{ID: "session.first", Context: Session, Title: "first message, keeping your draft", Keys: []string{"ctrl+home"}},
	{ID: "session.last", Context: Session, Title: "latest message, keeping your draft", Keys: []string{"ctrl+end"}},
	{ID: "session.message", Context: Session, Title: "read the full user message and attachments", Keys: []string{"ctrl+] enter", "alt+enter"}},
	{ID: "session.bottom", Context: Session, Title: "back to the latest", Keys: []string{"end"}},
	{ID: "session.toggle", Context: Session, Title: "open or close the selected row; type a space in the composer", Keys: []string{"space"}},
	{ID: "session.stash", Context: Session, Title: "set what's typed aside, or bring it back; it comes back after you send", Keys: []string{"ctrl+p"}},
	{ID: "session.history", Context: Session, Title: "what you set aside, sent, cleared and replaced", Keys: []string{"ctrl+r"}},
	{ID: "session.done", Context: Session, Title: "move the agent to Done", Keys: []string{"ctrl+d", "ctrl+] d"}},
	{ID: "session.hold", Context: Session, Title: "hold or release the queue", Keys: []string{"ctrl+] h", "alt+h"}},
	{ID: "session.rewind", Context: Session, Title: "rewind to the turn, or mark a file reviewed", Keys: []string{"ctrl+] r", "alt+r"}},
	{ID: "session.full", Context: Session, Title: "the picked changed file in full", Keys: []string{"ctrl+] v", "alt+v"}},
	{ID: "session.fork", Context: Session, Title: "fork from the turn", Keys: []string{"ctrl+] f"}, Runs: true},
	{ID: "session.copy", Context: Session, Title: "copy the answer or drawing", Keys: []string{"ctrl+] c"}, Runs: true},
	{ID: "session.sub.next", Context: Session, Title: "the next subagent run", Keys: []string{"shift+down", "alt+down"}},
	{ID: "session.sub.prev", Context: Session, Title: "the subagent run before", Keys: []string{"shift+up", "alt+up"}},
	{ID: "session.view.prev", Context: Session, Title: "the view before", Keys: []string{"["}},
	{ID: "session.view.next", Context: Session, Title: "the next view", Keys: []string{"]"}},
	{ID: "session.history.open", Context: Session, Title: "open all conversation turns", Keys: []string{"ctrl+] e"}, Runs: true},
	{ID: "session.history.close", Context: Session, Title: "close older turns, keeping the latest open", Keys: []string{"ctrl+] s"}, Runs: true},
	{ID: "session.verbose", Context: Session, Title: "more or less detail", Keys: []string{"ctrl+o"}},
	{ID: "session.stop", Context: Session, Title: "hide (stop), restart, switch or delete it", Keys: []string{"ctrl+x"}},
	{ID: "session.go", Context: Session, Title: "tell the agent to keep going", Keys: []string{"ctrl+b"}},
	{ID: "session.btw", Context: Session, Title: "a side question in a panel, and back to the chat", Keys: []string{"ctrl+] b"}, Runs: true},
	{ID: "session.background", Context: Session, Title: "background what the turn waits on", Keys: []string{"ctrl+] j"}, Runs: true},
	{ID: "session.sendmode", Context: Session, Title: "how enter sends while it works: queue, guide, or stop and send", Keys: []string{"ctrl+t"}},
	{ID: "session.mode", Context: Session, Title: "choose session permissions", Keys: []string{"ctrl+] p"}, Runs: true},
	{ID: "session.setup", Context: Session, Title: "choose this session’s model, effort and harness", Keys: []string{"shift+tab"}, Runs: true},
	{ID: "session.start", Context: Session, Title: "pick the next session's agent, model and effort, or merge the queued message", Keys: []string{"ctrl+] m", "alt+m"}},
	{ID: "session.separate", Context: Session, Title: "send the queue as one message or separately", Keys: []string{"ctrl+] o", "alt+o"}},
	{ID: "session.allow", Context: Session, Title: "answer the card yes: allow it, or continue at the reset", Keys: []string{"ctrl+] y", "alt+y"}},
	{ID: "session.always", Context: Session, Title: "allow it, and don't ask again", Keys: []string{"ctrl+] a", "alt+a"}},
	{ID: "session.deny", Context: Session, Title: "answer the card no", Keys: []string{"ctrl+] n", "alt+n"}},
	{ID: "session.look", Context: Session, Title: "the picked step's output as text, pretty or hex", Keys: []string{"v"}},
	{ID: "session.link", Context: Session, Title: "what to do with the picked step's file or link", Keys: []string{"o"}},
	{ID: "session.folder", Context: Session, Title: "choose where the agent works", Keys: []string{"ctrl+l"}},
	{ID: "session.needs", Context: Session, Title: "the next agent that needs you", Keys: []string{"ctrl+n"}},
	{ID: "session.split.less", Context: Session, Title: "less of the screen for the list", Keys: []string{"shift+left", "alt+left"}},
	{ID: "session.split.more", Context: Session, Title: "more of the screen for the list", Keys: []string{"shift+right", "alt+right"}},
	{ID: "session.editor", Context: Session, Title: "write what's typed in your editor", Keys: []string{"ctrl+g"}},
	{ID: "session.image", Context: Session, Title: "paste an image", Keys: []string{"ctrl+v"}},
	{ID: "session.undo", Context: Session, Title: "undo in the box", Keys: []string{"super+z", "ctrl+_", "ctrl+/"}},
	{ID: "session.redo", Context: Session, Title: "redo in the box", Keys: []string{"shift+super+z", "ctrl+y"}},
	{ID: "session.focus", Context: Session, Title: "back to Agents, and in again", Keys: []string{"tab", "{", "}"}},
	{ID: "session.list", Context: Session, Title: "Agents beside the Session", Keys: []string{"ctrl+6", "ctrl+^", "ctrl+shift+6"}},
}

// CommandID is the action that runs a # command.
func CommandID(name string) string { return "command:" + name }

// PluginID is the action that runs a plugin's command.
func PluginID(plugin, command string) string { return "plugin:" + plugin + "." + command }
